os: Visual Studio 2017
version: 1.0.{build}
build_script:
  - cmd: dotnet build /v:m /m .\StringCompactor.sln
after_build:
  - cmd: dotnet pack .\src\StringCompactor\StringCompactor.csproj
test_script:
  - cmd: dotnet test .\test\StringCompactorTests\StringCompactorTests.csproj
artifacts:
  - path: '**\bin\**\*.nupkg'